FROM python:3.8-slim-buster

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip3 install -r requirements.txt

COPY . .
ENV MONGODB_CONNECTION_URI="mongodb://mongo:27017/"

CMD [ "python3", "main.py" ]